create or replace database FINSERVAM_DEMO;

create or replace schema SAMPLE_DATA;

create or replace TABLE FINSERVAM_DEMO.SAMPLE_DATA.PM (
	PM VARCHAR(16777216),
	ID NUMBER(19,0)
);

create or replace TABLE FINSERVAM_DEMO.SAMPLE_DATA.TRADER (
	TRADER VARCHAR(16777216),
	PM VARCHAR(16777216),
	BUYING_POWER NUMBER(38,0)
);

create or replace TABLE FINSERVAM_DEMO.SAMPLE_DATA.TRADE (
	DATE DATE,
	SYMBOL VARCHAR(65535),
	EXCHANGE VARCHAR(1000),
	ACTION VARCHAR(25),
	CLOSE FLOAT,
	NUM_SHARES FLOAT,
	CASH FLOAT,
	TRADER VARCHAR(16777216),
	PM VARCHAR(16777216),
	COST_BASIS FLOAT
);

create or replace TABLE FINSERVAM_DEMO.SAMPLE_DATA.STOCK_HISTORY (
	SYMBOL VARCHAR(65535),
	DATE DATE,
	COMPANY VARCHAR(1000),
	EXCHANGE VARCHAR(1000),
	CLOSE FLOAT
);
